
    create table AVALIACAO (
        id bigint generated by default as identity,
        comentario varchar(1000),
        disciplina_id bigint not null,
        primary key (id)
    );

    create table CURSO (
        id bigint generated by default as identity,
        nome varchar(255) not null unique,
        primary key (id)
    );

    create table DISCIPLINA (
        id bigint generated by default as identity,
        nome varchar(255) not null,
        professor varchar(255) not null,
        curso_id bigint not null,
        primary key (id)
    );

    create table PERGUNTA (
        id bigint generated by default as identity,
        TEXTO varchar(255) not null unique,
        primary key (id)
    );

    create table RESPOSTA (
        id bigint generated by default as identity,
        nota integer not null,
        avaliacao_id bigint not null,
        pergunta_id bigint not null,
        primary key (id)
    );

    create table VALIDACAO (
        HASH varchar(512) not null,
        DATA_CRIACAO timestamp(6),
        DATA_VALIDACAO timestamp(6),
        TENTATIVAS_VALIDACAO integer,
        VALIDADO boolean not null,
        primary key (HASH)
    );

    alter table if exists AVALIACAO
       add constraint FKq21lbelcgg8yeyxsn67y2ghoa
       foreign key (disciplina_id)
       references disciplina;

    alter table if exists disciplina
       add constraint FKkhdiw1swjoa2ml3md0mt8g4sf
       foreign key (curso_id)
       references CURSO;

    alter table if exists RESPOSTA
       add constraint FKtg0qupfevdkx828fcj160lsl4
       foreign key (avaliacao_id)
       references AVALIACAO;

    alter table if exists RESPOSTA
       add constraint FKb86ld7inqykdiso1yvdy1cjyd
       foreign key (pergunta_id)
       references PERGUNTA;

    alter table if exists CURSO
       drop constraint if exists UKbdhliwglt8i7q1v80fb95vea9;

    alter table if exists CURSO
       add constraint UKbdhliwglt8i7q1v80fb95vea9 unique (nome);

    alter table if exists PERGUNTA
       drop constraint if exists UKdl0enf4tgn1tynce6def8x9d0;

    alter table if exists PERGUNTA
       add constraint UKdl0enf4tgn1tynce6def8x9d0 unique (TEXTO);
